# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  # os: ubuntu-lts-latest # Refers to the latest Ubuntu LTS version of Ubuntu available on Read the Docs, which may not match the latest Ubuntu LTS officially released.
  tools:
    # python: "3.11"
    python: "mambaforge-22.9"
    # You can also specify other tool versions:
    # nodejs: "19"
    # rust: "1.64"
    # golang: "1.19"
  jobs:
    post_create_environment:
      - git submodule update --init --recursive
      # - conda install conda-build conda-verify pytest
      # - conda build conda.recipe
      # - conda install -c ${CONDA_PREFIX}/conda-bld/ pyrte_rrtmgp
      - sudo apt install libnetcdff-dev
      - sudo apt install gfortran-10
      - sudo apt install python3-dev
      - sudo apt install cmake
      - pip install .

conda:
  environment: docs/environment-docs.yml

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
# formats:
#    - pdf
#    - epub

# Optional but recommended, declare the Python requirements required
# to build your documentation
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
# python:
#    install:
#    - requirements: docs/requirements-docs.txt
