# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: "ubuntu-24.04"
  tools:
    python: "mambaforge-23.11"
  apt_packages:
    - build-essential
    - ninja-build
  jobs:
    pre_build:
      - conda list
      - conda config --add channels conda-forge
      - conda info
      - export CONDA_BASE=$(conda info --base)  # Get the base Conda directory
      - export CONDA_BLD_PATH=$CONDA_BASE/conda-bld  # Construct the build path
      - conda build conda.recipe
      - ls $CONDA_BLD_PATH/linux-64  # Debug: List the contents of the build directory
      - conda index $CONDA_BLD_PATH  # Index the correct build directory
      - conda install -c file://$CONDA_BLD_PATH pyrte_rrtmgp

conda:
  environment: docs/environment-docs.yml
  # Python version to use in the conda environment is specified in this file.
  # when updating the tested Python versions, please also update README.md,
  # the conda.recipe/meta.yaml file, pyproject.toml, and the conda.yml file
  # for the GitHub Actions workflow

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
# formats:
#    - pdf
#    - epub

# Optional but recommended, declare the Python requirements required
# to build your documentation
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
# python:
#    install:
#   #  - requirements: docs/requirements-docs.txt
#    - method: pip
#      path: .
