# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /opt/rte-rrtmgp-python

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /opt/rte-rrtmgp-python

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /opt/rte-rrtmgp-python/CMakeFiles /opt/rte-rrtmgp-python//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /opt/rte-rrtmgp-python/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pyrte

# Build rule for target.
pyrte: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pyrte
.PHONY : pyrte

# fast build rule for target.
pyrte/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pyrte.dir/build.make CMakeFiles/pyrte.dir/build
.PHONY : pyrte/fast

#=============================================================================
# Target rules for targets named compile-rte-rrtmgp

# Build rule for target.
compile-rte-rrtmgp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 compile-rte-rrtmgp
.PHONY : compile-rte-rrtmgp

# fast build rule for target.
compile-rte-rrtmgp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compile-rte-rrtmgp.dir/build.make CMakeFiles/compile-rte-rrtmgp.dir/build
.PHONY : compile-rte-rrtmgp/fast

pybind_interface.o: pybind_interface.cpp.o

.PHONY : pybind_interface.o

# target to build an object file
pybind_interface.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pyrte.dir/build.make CMakeFiles/pyrte.dir/pybind_interface.cpp.o
.PHONY : pybind_interface.cpp.o

pybind_interface.i: pybind_interface.cpp.i

.PHONY : pybind_interface.i

# target to preprocess a source file
pybind_interface.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pyrte.dir/build.make CMakeFiles/pyrte.dir/pybind_interface.cpp.i
.PHONY : pybind_interface.cpp.i

pybind_interface.s: pybind_interface.cpp.s

.PHONY : pybind_interface.s

# target to generate assembly for a file
pybind_interface.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pyrte.dir/build.make CMakeFiles/pyrte.dir/pybind_interface.cpp.s
.PHONY : pybind_interface.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... compile-rte-rrtmgp"
	@echo "... pyrte"
	@echo "... pybind_interface.o"
	@echo "... pybind_interface.i"
	@echo "... pybind_interface.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

