#
# Python modules below are needed to run example notebook scripts
#
name: pyrte_dyamond_clouds
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python >=3.11,<3.13
  - pyrte_rrtmgp
  - dask
  - typing_extensions
  - jupyter
  - jupytext
  - pooch
  - cartopy
  - matplotlib

