package:
  name: pyrte_rrtmgp
  version: 0.0.7

source:
  path: ..

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - libuv >=1.44.2
    - cmake >=3.18
    - git >=2.44.0
    - ninja
    - python
  
  host:
    - python
    - pip
    # - libstdcxx-ng
    # - libgcc-ng
    - scikit-build-core
    - pybind11 >=2.10.0
    - rte_rrtmgp ==v1.9.1

  run:
    - python
    - numpy >=1.21.0
    - xarray >=2023.5.0
    - netcdf4 >=1.5.7
    - requests >=2.4.0
    - pytest >=7.4
    - rte_rrtmgp ==v1.9.1

test:
  imports:
    - pyrte_rrtmgp
  requires:
    - numpy >=1.21
    - pytest >=7.4
    - xarray >=2023.5.0
    - netcdf4 >=1.5.7
    - requests >=2.4.0
    - rte_rrtmgp ==v1.9.1
  commands:
    - pyrte_rrtmgp run_tests

about:
  summary: A Python interface to the RTE+RRTMGP Fortran software package.
  license_file: LICENSE
