package:
  name: pyrte_rrtmgp
  version: 0.1.3

source:
  path: ..

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - cmake >=3.18
    - git >=2.44.0
    - libuv >=1.44.2
    - ninja >=1.10
    - python

  host:
    - numpy >=1.21.0
    - pip
    - pybind11 >=2.10.0,<3.0.0
    - python
    - rte_rrtmgp ==1.9.1
    - scikit-build-core

  run:
    - netcdf4 >=1.7.2
    - numpy >=1.21.0
    - pytest >=7.4
    - pytest-cov >=3.0
    - python
    - requests >=2.4.0
    - rte_rrtmgp ==1.9.1
    - xarray >=2023.5.0
    - dask >=2023.5.0

test:
  imports:
    - pyrte_rrtmgp
  requires:
    - netcdf4 >=1.7.2
    - numpy >=1.21
    - pytest >=7.4
    - pytest-cov >=3.0
    - requests >=2.4.0
    - rte_rrtmgp ==1.9.1
    - xarray >=2023.5.0
    - dask >=2023.5.0
  commands:
    - pyrte_rrtmgp run_tests

about:
  home: https://github.com/earth-system-radiation/pyRTE-RRTMGP
  summary: A Python interface to the RTE+RRTMGP Fortran software package.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://pyrte-rrtmgp.readthedocs.io/
