package:
  name: pyrte_rrtmgp
  version: 0.0.6

source:
  path: ..

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    # - {{ compiler('c') }}    # [unix]
    # - {{ compiler('cxx') }}  # [unix]
    - gfortran_linux-64   # [linux]
    - gfortran_osx-64     # [osx and not arm64]
    - gfortran_osx-arm64  # [osx and arm64]
    - m2w64-gcc-fortran   # [win]
    # - gcc_impl_win-64=13.2.0       # [win]
    # - gfortran_impl_win-64=13.2.0  # [win]
    # - libgomp=13.2.0               # [win]
    # - libgcc=13.2.0                # [win]
    - libuv==1.44.2
    - cmake==3.26.4
    - git==2.44.0
    - ninja
    - rte-rrtmgp

  host:
    - python
    - pip
    - scikit-build-core
    - pybind11 >=2.10.0
    - numpy >=1.21.0
    - pytest>=7.4
    - liblief==0.14.1

  run:
    - python
    - numpy >=1.21.0
    - xarray >=2023.5.0
    - netcdf4 >=1.7.2
    - requests>=2.4.0
    - pytest>=7.4
    - liblief==0.14.1

test:
  imports:
    - pyrte_rrtmgp
  requires:
    - numpy>=1.21
    - pytest>=7.4
    - xarray >=2023.5.0
    - netcdf4 >=1.7.2
    - requests>=2.4.0
  commands:
    - pyrte_rrtmgp run_tests

about:
  summary: A Python interface to the RTE+RRTMGP Fortran software package.
  license_file: LICENSE
