name: Build Sphinx Documentation

on:
  push:
    branches:
      - main
    paths:
    - 'docs/**/*'
  pull_request:
    branches:
      - main
    paths:
    - 'docs/**/*'

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11' # Specify the Python version you need for your project

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docs/requirements-docs.txt

    - name: Build Sphinx Documentation
      run: |
        cd docs
        sphinx-build -b html source build/html

    # # Uncomment the following lines to check for build warnings
    # - name: Check for build errors
    #   run: |
    #       if [ -s "build/html/warnings.txt" ]; then
    #         echo "Build failed with errors."
    #         exit 1
    #       fi
